### ISSUE TITLE
PORT 8080 in use after unsuccessful start

### ISSUE THREAD

**Issue by s0170071** [bluezio/ipwebcam-gst#101]
I use the USB connection and a S4mini
When I start the script and the server on the camera is not started, I get a window complaining that it is not reachable. 

Any attemt to start the script again complains the port 8080 is busy. I guess it has been forwarded but not cleared when the error occured.

**Comment by s0170071** [comment]
on the command line, the command:
`adb forward --remove tcp:8080`
frees the port.

**Comment by bluezio** [comment]
c24f638 now detects when there is a lingering ADB forward that should be removed, and asks the user if they'd like that to be removed.
