### ISSUE TITLE
Browser streaming works, but not with chat apps

### ISSUE THREAD

**Issue by yannisdran** [bluezio/ipwebcam-gst#106]
I was able to stream ipwebcam from a Samsung S3 to Lubuntu Firefox easily, but what bugs me, is that I cannot make it stream to Zoom (or any other app I guess). The only device available in Zoom's settings for camera is a "Dummy Video Device (0x0000)" showing only black.
When I go to the folder that gst is downloaded and run ./run-videochat.sh, there is a message popping out as the following:
```
The IP Webcam audio feed is not reachable at http://127.0.0.1:8080/audio.wav.
The IP Webcam video feed is not reachable at http://127.0.0.1:8080/videofeed.
Please install and open IP Webcam in your phone and start the server.
Make sure that values of variables IP, PORT, CAPTURE_STREAM in this script are equal with settings in IP Webcam
```

**Comment by bluezio** [comment]
You need to check the option in IP Webcam that records audio as well: it may not be on by default.
