### ISSUE TITLE
USB Delay about 2 seconds

### ISSUE THREAD

**Issue by mavyfaby** [bluezio/ipwebcam-gst#107]
I am able to connect the android phone's mic to PC but the USB delay is about 2 seconds.

**Comment by bluezio** [comment]
You could try disabling echo cancellation with the `-C` option:

```shell
./run-videochat.sh -C
```

Other than that, we don't really do much processing of the audio: it depend on your type of connection (Wi-Fi always has some lag, and even USB can be slow sometimes depending on the phone or the chosen width/height).
