### ISSUE TITLE
Video device /dev/video1 not usable

### ISSUE THREAD

**Issue by ovidiub13** [bluezio/ipwebcam-gst#19]
Either through wireless, or adb, the video device cannot be opened in VLC, and Google Hangouts does not see it.

**Comment by bluezio** [comment]
Have you tried the troubleshooting steps detailed in the script?

**Comment by ovidiub13** [comment]
No, I have not. I'm sorry, but I searched for a different project, and found a different solution for this. So I have no further feedback for this, for now.

I'll try it again in a few days, or weeks. (I still need this functionality)
