### ISSUE TITLE
Double quote array expansions to avoid re-splitting elements. [SC2068]

### ISSUE THREAD

**Issue by inTagger** [bluezio/ipwebcam-gst#24]
```bash
send_intent() {
    start_adb && "$ADB" $ADB_FLAGS shell am start -a android.intent.action.MAIN -n $@
}
```

> Double quote array expansions to avoid re-splitting elements. [SC2068] at line 175 col 84

**Comment by bluezio** [comment]
I assume this is coming from a static analysis tool?

This is a false positive: we want that re-splitting in this case.
