### ISSUE TITLE
user and password in prepare-videochat.sh 

### ISSUE THREAD

**Issue by calda1980** [bluezio/ipwebcam-gst#49]
when I set user and password in IP Webcam,  prepare-videochat.sh script does not request for user and pass. how I set that in the script?
Thanks.

**Comment by bluezio** [comment]
I would suggest trying out the user-id and user-pw options to the various invocations of souphttpsrc:

https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-souphttpsrc.html#GstSoupHTTPSrc--user-id

You'll have to edit the `pipeline_video` and `pipeline_audio` functions in the script accordingly.

**Comment by bluezio** [comment]
No response from the user: closing for now.
