### ISSUE TITLE
script modified but error on Debian buster

### ISSUE THREAD

**Issue by hypsinom** [bluezio/ipwebcam-gst#51]
I don't found the way to modify the script to recognize rightly my version of debian. So I modified it differently by forcing the gstreamer to the version 1.0.  

here's the error

> Définition du pipeline à PAUSED...
Le pipeline est actif et n’a pas besoin de phase PREROLL…
Contexte de l’élément « souphttpsrc0 » : gst.soup.session=context, session=(SoupSession)NULL, force=(boolean)false;
Passage du pipeline à la phase PLAYING…
New clock: GstSystemClock
/GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:src: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)44100, channels=(int)1
/GstPipeline:pipeline0/GstQueue:queue0.GstPad:sink: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)44100, channels=(int)1
/GstPipeline:pipeline0/GstQueue:queue0.GstPad:sink: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)44100, channels=(int)1
Redistribution de latence…
/GstPipeline:pipeline0/GstPulseSink:pulsesink0.GstPad:sink: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)44100, channels=(int)1
ERREUR : de l’élément /GstPipeline:pipeline0/GstSoupHTTPSrc:souphttpsrc1 : Internal data stream error.
Information de débogage supplémentaire :
gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstSoupHTTPSrc:souphttpsrc1:
streaming stopped, reason not-linked (-1)
EOS à la fermeture est activé -- attente d’EOS après erreur
Attente d’EOS.

here's the modified script 

https://pastebin.com/G6LQwXmA

**Comment by nyov** [comment]
Same issue. The `if` clause [on line 325](https://github.com/bluezio/ipwebcam-gst/blob/2ddbe5e06544be0a457bde9ff9b17582496af6f0/prepare-videochat.sh#L325-L328) is done wrong. Debian version 9 is < than Ubuntu version 14.04

`set -x` shows this here (excerpt):
```
+ can_run lsb_release
+ which lsb_release
++ lsb_release -i
++ cut -f2 -d :
+ DIST='	Debian'
++ lsb_release -r
++ cut -f2 -d :
+ RELEASE='	9.4'
+ '[' -f /etc/debian_version ']'
+ DIST=Debian
++ perl -ne 'chomp; if(m:(jessie|testing|sid):){print "8.0"}elsif(m:[\d\.]+:){print}else{print "0.0"}'
+ RELEASE=9.4
+ GST_VER=0.10
+ GST_VIDEO_CONVERTER=ffmpegcolorspace
+ GST_VIDEO_MIMETYPE=video/x-raw-yuv
+ GST_VIDEO_FORMAT='format=(fourcc)YUY2'
+ GST_AUDIO_MIMETYPE=audio/x-raw-int
+ GST_AUDIO_FORMAT=width=16,depth=16,endianness=1234,signed=true
+ GST_AUDIO_RATE=rate=44100
+ GST_AUDIO_CHANNELS=channels=1
+ GST_AUDIO_LAYOUT=
+ GST_1_0_AUDIO_FORMAT=format=S16LE
+ GST_0_10_VIDEO_MIMETYPE=video/x-raw-yuv
+ GST_0_10_VIDEO_FORMAT='format=(fourcc)YUY2'
+ can_run bc
+ which bc
+ '[' Debian = Debian ']'
++ echo '9.4 >= 8.0'
++ bc
+ '[' 1 -eq 1 ']'
++ echo '9.4 >= 14.04'
++ bc
+ '[' 0 -eq 1 ']'
+ '[' Debian = LinuxMint ']'
+ '[' Debian = Arch ']'
```

Otherwise thanks a lot for the script, it's awesome.
