### ISSUE TITLE
Download from AUR

### ISSUE THREAD

**Issue by CalizoNilo** [bluezio/ipwebcam-gst#55]
I cannot find the package listed (ipwebcam-gst-git) in the instructions in the AUR. 
Any help would be appreciated.

**Comment by bluezio** [comment]
The AUR package was contributed by another developer - unfortunately, I cannot find it anymore either. I have removed the reference to it from the main README. Sorry, I don't really use Arch!

**Comment by barfin** [comment]
I made an AUR package, and I'm using right now, everything works as expected
https://aur.archlinux.org/packages/ipwebcam/
