### ISSUE TITLE
Can't open /dev/video0

### ISSUE THREAD

**Issue by nickmh** [bluezio/ipwebcam-gst#6]
Hi Antonio,

I'm not even sure this is an IPWebCam issue.

I'm unable to open the stream from /dev/video0 I've tried Cheese, VLC, Camorama

VLC messages says...
VLC is unable to open the MRL 'v4l2:///dev/video0'. Check the log for details.
Which reveals...
main debug: adding item `v4l2:///dev/video0' ( v4l2:///dev/video0 )
main debug: rebuilding array of current - root Playlist
main debug: rebuild done - 3 items, index 1
main debug: processing request item: v4l2:///dev/video0, node: null, skip: 0
main debug: resyncing on v4l2:///dev/video0
main debug: v4l2:///dev/video0 is at 2
main debug: starting playback of the new playlist item
main debug: resyncing on v4l2:///dev/video0
main debug: v4l2:///dev/video0 is at 2
main debug: creating new input thread
main debug: Creating an input for 'v4l2:///dev/video0'
main debug: meta ok for (null), need to fetch art
main debug: TIMER input launching for 'v4l2:///dev/video0' : 20667.072 ms - Total 20667.072 ms / 1 intvls (Avg 20667.072 ms)
main debug: using timeshift granularity of 50 MiB, in path '/tmp'
main debug:`v4l2:///dev/video0' gives access `v4l2' demux`' path `/dev/video0'
main debug: creating demux: access='v4l2' demux='' location='/dev/video0' file='/dev/video0'
main debug: looking for access_demux module: 1 candidate
v4l2 debug: opening device '/dev/video0'
v4l2 debug: trying library V4L2
main debug: no access_demux module matching "v4l2" could be loaded
main debug: TIMER module_need() : 0.208 ms - Total 0.208 ms / 1 intvls (Avg 0.208 ms)
main debug: creating access 'v4l2' location='/dev/video0', path='/dev/video0'
main debug: looking for access module: 1 candidate
v4l2 debug: opening device '/dev/video0'
v4l2 debug: trying library V4L2
main debug: no access module matching "v4l2" could be loaded
main debug: TIMER module_need() : 0.057 ms - Total 0.057 ms / 1 intvls (Avg 0.057 ms)
main error: open of`v4l2:///dev/video0' failed
main debug: looking for meta fetcher module: 1 candidate
lua debug: Trying Lua scripts in /home/nick/.local/share/vlc/lua/meta/fetcher
lua debug: Trying Lua scripts in /usr/lib/vlc/lua/meta/fetcher
lua debug: Trying Lua playlist script /usr/lib/vlc/lua/meta/fetcher/tvrage.luac
main debug: using meta fetcher module "lua"
main debug: TIMER module_need() : 0.738 ms - Total 0.738 ms / 1 intvls (Avg 0.738 ms)
main debug: removing module "lua"
main debug: searching art for v4l2:///dev/video0
main debug: looking for art finder module: 2 candidates
lua debug: Trying Lua scripts in /home/nick/.local/share/vlc/lua/meta/art
lua debug: Trying Lua scripts in /usr/lib/vlc/lua/meta/art
lua debug: Trying Lua playlist script /usr/lib/vlc/lua/meta/art/00_musicbrainz.luac
lua debug: Trying Lua playlist script /usr/lib/vlc/lua/meta/art/01_googleimage.luac
main debug: dead input
main debug: changing item without a request (current 2/3)
main debug: nothing to play
qt4 debug: Adding a new MRL to recent ones: v4l2:///dev/video0
lua debug: Trying Lua playlist script /usr/lib/vlc/lua/meta/art/02_frenchtv.luac
lua debug: Trying Lua playlist script /usr/lib/vlc/lua/meta/art/03_lastfm.luac
lua debug: Trying Lua scripts in /usr/share/vlc/lua/meta/art
main debug: no art finder module matching "any" could be loaded
main debug: TIMER module_need() : 1.056 ms - Total 1.056 ms / 1 intvls (Avg 1.056 ms)
main debug: art not found for v4l2:///dev/video0

I've tried googling and can't come up with anything that either works or is applicable.

I think I just need a clue to chase down.

Regards
Nick

**Comment by Purplewelshy** [comment]
When you say ' It was Audio that was misbehaving.' could you explain a bit more please, like how it was misbehaving and what you did to stop it misbehaving.

Thanks,
Chris.
