### ISSUE TITLE
Setting FPS cap fails. Internal data stream error.

### ISSUE THREAD

**Issue by BifbofII** [bluezio/ipwebcam-gst#70]
I have an issue with your script, but I am not quite shure if the problem lies within your script.
When I try to run the script, I get the ouput in the log file, which is attached here.

<details>
<summary>feed.log</summary>

```
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Got context from element 'souphttpsrc0': gst.soup.session=context, session=(SoupSession)NULL, force=(boolean)false;
Setting pipeline to PLAYING ...
New clock: GstSystemClock
/GstPipeline:pipeline0/GstDecodeBin:decodebin0.GstGhostPad:sink.GstProxyPad:proxypad0: caps = image/jpeg
/GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstTypeFindElement:typefind.GstPad:src: caps = image/jpeg
/GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstJpegDec:jpegdec0.GstPad:sink: caps = image/jpeg
/GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstTypeFindElement:typefind.GstPad:sink: caps = image/jpeg
/GstPipeline:pipeline0/GstDecodeBin:decodebin0.GstGhostPad:sink: caps = image/jpeg
/GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstJpegDec:jpegdec0.GstPad:src: caps = video/x-raw, format=(string)I420, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, colorimetry=(string)1:4:0:0, framerate=(fraction)0/1
/GstPipeline:pipeline0/GstDecodeBin:decodebin0.GstDecodePad:src_0.GstProxyPad:proxypad1: caps = video/x-raw, format=(string)I420, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, colorimetry=(string)1:4:0:0, framerate=(fraction)0/1
ERROR: from element /GstPipeline:pipeline0/GstSoupHTTPSrc:souphttpsrc0: Internal data stream error.
Additional debug info:
../gstreamer/libs/gst/base/gstbasesrc.c(3072): gst_base_src_loop (): /GstPipeline:pipeline0/GstSoupHTTPSrc:souphttpsrc0:
streaming stopped, reason not-negotiated (-4)
EOS on shutdown enabled -- waiting for EOS after Error
Waiting for EOS...
ERROR: from element /GstPipeline:pipeline0/GstQueue:queue0: Internal data stream error.
Additional debug info:
../gstreamer/plugins/elements/gstqueue.c(988): gst_queue_handle_sink_event (): /GstPipeline:pipeline0/GstQueue:queue0:
streaming stopped, reason not-negotiated (-4)
```
</details>

This output is produced by the following GStreamer pipeline:
```
souphttpsrc location=http://127.0.0.1:8080/videofeed do-timestamp=true is-live=true ! queue ! multipartdemux ! decodebin ! videoconvert ! videoscale ! video/x-raw,format=YUY2,width=1920,height=1080,framerate=24/1 ! v4l2sink device=/dev/video3 sync=true
```

After some trial and arrow I was able to narrow the problem down to the definition of the framerate in the pipeline. If I remove the part about the framerate, GStreamer returns no error and I can read the v4l2loopback device in VLC (but not in Skype for some reason).

I tried the following:
* Trouble shooting section in the script: everything works as expected
* Remove other video devices: same problem
* Different frame rate values: did not find a working value
* Limit framerate in IP Webcam: no good results

I am running arch linux with the following package versions:
* Kernel: `5.5.13-arch2-1`
* `v4l2loopback-dkms`: `0.12.5-1`
* `v4l-utils`: `1.18.0-1`
* `gstreamer`: `1.16.2-1`
* `gst-plugins-base`: `1.16.2-1`
* `gst-plugins-base-libs`: `1.16.2-1`
* `gst-plugins-good`: `1.16.2-3`

Maybe you have some idea where the error might be coming from. Thank you for your work on the script.

**Comment by bluezio** [comment]
I dropped videorate as part of the suggestions from #64 to make playback smoother, but it seems that the `framerate=24/1` part requires `videorate` to work. I've dropped the framerate cap from the script, so we do not do any type of FPS adjustment now. That should have fixed the issue: feel free to reopen if you still have problems.
