### ISSUE TITLE
webcam video is paused

### ISSUE THREAD

**Issue by jhunnies** [bluezio/ipwebcam-gst#79]
Managed to get it running on Linux mint 19.3. Compiled the latest v4l2loopback from https://github.com/bluetiger9/v4l2loopback but the webcam video is paused.

**Comment by bluezio** [comment]
Which tool are you using? Zoom? Skype?

**Comment by jhunnies** [comment]
I used VLC open capture device.

**Comment by bluezio** [comment]
I cannot reproduce this on my Ubuntu 20.04 machine: I've tried running the script and opening it on VLC's "Open capture device" option, and it works fine. Closing for now: feel free to reopen if this is still an issue, but we'd have to look into the specifics of your system.
