### ISSUE TITLE
Ported script to perl

### ISSUE THREAD

**Issue by Duoxilian** [bluezio/ipwebcam-gst#82]
I needed some configuration options for my setup, and I found it easier to understand the script by porting it to perl. If you are interested, I can post it. I have only tested it on ubuntu 18.04, though.

**Comment by bluezio** [comment]
I can have a look :-). I'd only be able to merge it if it was a one-to-one replacement of the current script (including the Arch-specific bits), however. If it's substantially different, it may be better to create a new project for it.

**Comment by Duoxilian** [comment]
Sorry for the delay. I ported your "arch-specific bits" but without testing. However, there are extensions, as I wanted to control more of the webcam from the parameters of the script rather than having to make changes in the script itself.

**Comment by bluezio** [comment]
Closing this, as @battarsa kindly split the script into two and it's a bit more manageable now, still in Bash :-). @battarsa also contributed command-line flags for the "run" half.
