### ISSUE TITLE
Port Forward persisting after script ends

### ISSUE THREAD

**Issue by bellalistair** [bluezio/ipwebcam-gst#87]
Running the script and then attempting to run again results in an error that the port is in use.
Adding
"$ADB" $ADB_FLAGS forward --remove tcp:$PORT
before
echo "Disconnected from IP Webcam. Have a nice day!"

Solves the issue, not sure if there is a reason for not doing so? Or if this is indicative of a different issue on my machine.

Thanks for all the work on this.

**Comment by bluezio** [comment]
Oops! I just forgot to do it :-D. I've added this bit.
