### ISSUE TITLE
No longer supported for Ubuntu 20.04+?

### ISSUE THREAD

**Issue by ThisIsanAlt** [bluezio/ipwebcam-gst#95]
Commands like `sudo ./install-videochat.sh` don't seem to be supported on ubuntu 20.04+. Running the command returns `sudo: ./install-videochat.sh: command not found` and the drivers are not installed.

Is there a fix on the way or am I doing something wrong?

**Comment by sigboe** [comment]
As a fedora user I just read the script which packages it needed and installed them

**Comment by ThisIsanAlt** [comment]
im an idiot - you have to cd into the folder first
